<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LANSA-TEST" failures="1" tests="3" name="com.fusioncharts.apitest.RealTimeAPIsAutoFeed" time="26.258" errors="0" timestamp="25 Aug 2020 09:43:03 GMT">
  <testcase classname="com.fusioncharts.apitest.RealTimeAPIsAutoFeed" name="verifyChartIsRenderedRealTimeAPIsAutoFeed" time="3.006"/>
  <testcase classname="com.fusioncharts.apitest.RealTimeAPIsAutoFeed" name="verifyAPIRealTimeAPIsAutoFeed" time="23.251">
    <failure message="rtarea expected to get updated data expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: rtarea expected to get updated data expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.fusioncharts.apitest.RealTimeAPIsAutoFeed.verifyAPIRealTimeAPIsAutoFeed(RealTimeAPIsAutoFeed.java:124)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- verifyAPIRealTimeAPIsAutoFeed -->
  <testcase classname="com.fusioncharts.apitest.RealTimeAPIsAutoFeed" name="verifyAPIExistsInDataSheetRealTimeAPIsAutoFeed" time="0.001"/>
</testsuite> <!-- com.fusioncharts.apitest.RealTimeAPIsAutoFeed -->
